#name, main, version and api are required
name: JunkBayCommando
main: Endermanbugzjfc\JunkBayCommando\MainClass
src-namespace-prefix: Endermanbugzjfc\JunkBayCommando
version: 0.0.1
api: 4.0.0

load: POSTWORLD
author: Endermanbugzjfc
description: Example plugin showing the new API
website: https://github.com/Endermanbugzjfc/JunkBayCommando
commands:
  example:
    description: Example command
    usage: "/example"
    permission: junkbaycommando.command.example
permissions:
  junkbaycommando.command.example:
    description: "Allows the user to run the example command"
    default: true
